theme = "mytheme"

[editor]
line-number = "relative"
text-width = 80
auto-info = false
true-color = true
color-modes = true
auto-format = false
cursorline = true
completion-replace = true


[editor.file-picker]
max-depth = 6

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
C-j = "save_selection"
C-s = ":w" 
C-A-F = ":fmt"
A-h = ":toggle lsp.display-inlay-hints"

[keys.insert]
C-s = ":w" 
C-A-F = ":fmt"
A-h = ":toggle lsp.display-inlay-hints"
